# fly.toml file generated for weekbot

app = "weekbot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ewr"

[env]
  PRIMARY_REGION = "ewr"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  entrypoint = ["litefs", "mount", "--", "./main"]

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]