# fly.toml file generated for weekbot on 2022-09-12T19:47:55-04:00

app = "weekbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []
primary_region = "ewr"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = ["./main"]
  entrypoint = ["litefs", "mount", "--"]
  exec = []

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[build]
  dockerfile = "Dockerfile"

